/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.form;

import java.awt.BorderLayout;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author MARINA
 */
public class FMain extends javax.swing.JFrame {

    private static FMain instance;

    /**
     * Creates new form Fmain
     */
    private FMain() {
        initComponents();
        addPanelStatus();
        maximizeForm();
    }

    public static FMain getInstance() {
        if (instance == null) {
            instance = new FMain();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMain = new javax.swing.JPanel();
        jPnlUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuStudent = new javax.swing.JMenu();
        jMenuItemStudentNew = new javax.swing.JMenuItem();
        jMenuItemStudentSearch = new javax.swing.JMenuItem();
        jMenuDiplomskiRad = new javax.swing.JMenu();
        jMenuItemDiplomskiRad = new javax.swing.JMenuItem();
        jMenuTemaDiplomskogRada = new javax.swing.JMenu();
        jMenuItemTemaDiplomskogRadaNew = new javax.swing.JMenuItem();
        jMenuItemTemaDiplomskogRadaSearch = new javax.swing.JMenuItem();
        jMenuConfiguration = new javax.swing.JMenu();
        jMenuItemDatabase = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPnlMainLayout = new javax.swing.GroupLayout(jPnlMain);
        jPnlMain.setLayout(jPnlMainLayout);
        jPnlMainLayout.setHorizontalGroup(
            jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        jPnlMainLayout.setVerticalGroup(
            jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        getContentPane().add(jPnlMain, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Logged in user:");

        javax.swing.GroupLayout jPnlUserLayout = new javax.swing.GroupLayout(jPnlUser);
        jPnlUser.setLayout(jPnlUserLayout);
        jPnlUserLayout.setHorizontalGroup(
            jPnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlUserLayout.setVerticalGroup(
            jPnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLblUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlUser, java.awt.BorderLayout.PAGE_START);

        jMenuStudent.setText("Student");

        jMenuItemStudentNew.setText(" New");
        jMenuStudent.add(jMenuItemStudentNew);

        jMenuItemStudentSearch.setText(" Search");
        jMenuStudent.add(jMenuItemStudentSearch);

        jMenuBar1.add(jMenuStudent);

        jMenuDiplomskiRad.setText("Diplomski rad");

        jMenuItemDiplomskiRad.setText("Diplomski rad");
        jMenuDiplomskiRad.add(jMenuItemDiplomskiRad);

        jMenuBar1.add(jMenuDiplomskiRad);

        jMenuTemaDiplomskogRada.setText("Tema diplomskog rada");

        jMenuItemTemaDiplomskogRadaNew.setText("New");
        jMenuTemaDiplomskogRada.add(jMenuItemTemaDiplomskogRadaNew);

        jMenuItemTemaDiplomskogRadaSearch.setText("Search");
        jMenuTemaDiplomskogRada.add(jMenuItemTemaDiplomskogRadaSearch);

        jMenuBar1.add(jMenuTemaDiplomskogRada);

        jMenuConfiguration.setText("Configuration");

        jMenuItemDatabase.setText("Database");
        jMenuConfiguration.add(jMenuItemDatabase);

        jMenuBar1.add(jMenuConfiguration);

        jMenuAbout.setText("About");
        jMenuBar1.add(jMenuAbout);

        jMenuAccount.setText("Account");

        jMenuItemLogOut.setText("Log out");
        jMenuAccount.add(jMenuItemLogOut);

        jMenuBar1.add(jMenuAccount);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblUser;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JMenu jMenuDiplomskiRad;
    private javax.swing.JMenuItem jMenuItemDatabase;
    private javax.swing.JMenuItem jMenuItemDiplomskiRad;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemStudentNew;
    private javax.swing.JMenuItem jMenuItemStudentSearch;
    private javax.swing.JMenuItem jMenuItemTemaDiplomskogRadaNew;
    private javax.swing.JMenuItem jMenuItemTemaDiplomskogRadaSearch;
    private javax.swing.JMenu jMenuStudent;
    private javax.swing.JMenu jMenuTemaDiplomskogRada;
    private javax.swing.JPanel jPnlMain;
    private javax.swing.JPanel jPnlUser;
    // End of variables declaration//GEN-END:variables
    private JPanel pStatus;

    private void addPanelStatus() {
        pStatus = new PStatus();
        pStatus.setVisible(true);
        this.add(pStatus, BorderLayout.SOUTH);
    }

    public void setUseCaseMessage(String useCaseMessage) {
        ((PStatus) pStatus).setUseCaseMessage(useCaseMessage);
    }


    private void maximizeForm() {
        setExtendedState(MAXIMIZED_BOTH);
    }

    public JMenuItem getMenuItemStudentNew() {
        return jMenuItemStudentNew;
    }

    public JMenuItem getMenuItemStudentSearch() {
        return jMenuItemStudentSearch;
    }

    public javax.swing.JMenuItem getjMenuItemDiplomskiRad() {
        return jMenuItemDiplomskiRad;
    }

    public javax.swing.JMenuItem getjMenuItemLogOut() {
        return jMenuItemLogOut;
    }

    public javax.swing.JMenuItem getjMenuItemStudentNew() {
        return jMenuItemStudentNew;
    }

    public javax.swing.JMenuItem getjMenuItemStudentSearch() {
        return jMenuItemStudentSearch;
    }

    public javax.swing.JMenuItem getjMenuItemTemaDiplomskogRadaNew() {
        return jMenuItemTemaDiplomskogRadaNew;
    }

    public javax.swing.JMenuItem getjMenuItemTemaDiplomskogRadaSearch() {
        return jMenuItemTemaDiplomskogRadaSearch;
    }
    
    
}
