/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.form;

import rs.ac.bg.fion.silab.gui.general.GeneralGUISearch;
import rs.ac.bg.fion.silab.gui.general.GeneralGUI;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;



/**
 *
 * @author MARINA
 */
public class FStudentSearch extends javax.swing.JDialog implements GeneralGUI,GeneralGUISearch{

    /**
     * Creates new form FStudent
     */
    public FStudentSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initButtons();
        initPanels();
        pack();
    }

    private void initPanels() {
        basicSearchPanel = new PStudentBasicSearch();
        advancedSearchPanel = new PStudentSearchAdvanced();
        basicSearchPanel.setVisible(false);
        advancedSearchPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorth = new javax.swing.JPanel();
        jPanelFindById = new javax.swing.JPanel();
        jCheckBoxAdvancedSearch = new javax.swing.JCheckBox();
        jCheckBoxBasicSearch = new javax.swing.JCheckBox();
        jTxtBrojIndeksa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblStudents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelNorth.setMinimumSize(new java.awt.Dimension(0, 80));
        jPanelNorth.setPreferredSize(new java.awt.Dimension(801, 60));
        jPanelNorth.setLayout(new javax.swing.BoxLayout(jPanelNorth, javax.swing.BoxLayout.Y_AXIS));

        jPanelFindById.setPreferredSize(new java.awt.Dimension(1017, 60));

        jCheckBoxAdvancedSearch.setText("Advanced search");

        jCheckBoxBasicSearch.setText("Basic Search");

        jLabel1.setText("Broj indeksa:");

        javax.swing.GroupLayout jPanelFindByIdLayout = new javax.swing.GroupLayout(jPanelFindById);
        jPanelFindById.setLayout(jPanelFindByIdLayout);
        jPanelFindByIdLayout.setHorizontalGroup(
            jPanelFindByIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFindByIdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtBrojIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jCheckBoxAdvancedSearch)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxBasicSearch)
                .addGap(0, 231, Short.MAX_VALUE))
        );
        jPanelFindByIdLayout.setVerticalGroup(
            jPanelFindByIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFindByIdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFindByIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtBrojIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxAdvancedSearch)
                    .addComponent(jCheckBoxBasicSearch))
                .addGap(21, 21, 21))
        );

        jPanelNorth.add(jPanelFindById);

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.PAGE_START);

        jTblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblStudents);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxAdvancedSearch;
    private javax.swing.JCheckBox jCheckBoxBasicSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFindById;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblStudents;
    private javax.swing.JTextField jTxtBrojIndeksa;
    // End of variables declaration//GEN-END:variables
    private PStudentBasicSearch basicSearchPanel;
    private PStudentSearchAdvanced advancedSearchPanel;
    private PButtonsSearch jPanelButtons;

    
    public JTable getTable(){
        return jTblStudents;
    }



    @Override
    public void close() {
        dispose();
    }

    @Override
    public void setMessage(String signal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public JCheckBox getBasicSearchCheckbox() {
        return jCheckBoxBasicSearch;
    }

    @Override
    public JCheckBox getAdvancedSearchCheckbox() {
        return jCheckBoxAdvancedSearch;
    }

    @Override
    public void addBasicSearchPanel() {
        
        jPanelNorth.add(basicSearchPanel, BoxLayout.Y_AXIS);
        basicSearchPanel.setVisible(true);
        resizeSearchPanel();

    }

    @Override
    public void addAdvancedSearchPanel() {
        jPanelNorth.add(advancedSearchPanel, BoxLayout.Y_AXIS);
        advancedSearchPanel.setVisible(true);
        resizeSearchPanel();
    }

    @Override
    public void removeBasicSearchPanel() {
        jPanelNorth.remove(basicSearchPanel);
        basicSearchPanel.setVisible(false);
        resizeSearchPanel();
    }

    
    @Override
    public void removeAdvancedSearchPanel() {
         advancedSearchPanel.setVisible(false);
         jPanelNorth.remove(advancedSearchPanel);
         resizeSearchPanel();
    }

    private void resizeSearchPanel() {

        int height = jPanelFindById.getPreferredSize().height;

        if(basicSearchPanel.isVisible()){
            height += basicSearchPanel.getPreferredSize().height;
        }
        if(advancedSearchPanel.isVisible()){
            height += advancedSearchPanel.getPreferredSize().height;
        }
        jPanelNorth.setPreferredSize(new Dimension(WIDTH, height));
        revalidate();
    }

    public JTextField getjTxtBrojIndeksa() {
        return jTxtBrojIndeksa;
    }

    public PStudentBasicSearch getBasicSearchPanel() {
        return basicSearchPanel;
    }

    public PStudentSearchAdvanced getAdvancedSearchPanel() {
        return advancedSearchPanel;
    }

    @Override
    public JButton getView() {
        return jPanelButtons.getjBtnView();
    }
    @Override
    public JButton getSelect(){
        return jPanelButtons.getjBtnSelect();
    }

    private void initButtons() {
        jPanelButtons = new PButtonsSearch();
        jPanelButtons.setVisible(true);
        this.add(jPanelButtons, BorderLayout.SOUTH);
    }
    
}
