/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.form;

import rs.ac.bg.fion.silab.gui.general.GeneralGUINew;
import rs.ac.bg.fion.silab.gui.general.GeneralGUI;
import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author MARINA
 */
public class FTemaDiplomskogRadaNew extends javax.swing.JDialog implements GeneralGUI, GeneralGUINew {

    /**
     * Creates new form FTemaDiplomskogRada
     */
    public FTemaDiplomskogRadaNew(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initButtonsNew();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTeme = new javax.swing.JTable();
        jBtnAdd = new javax.swing.JButton();
        jBtnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jTableTeme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableTeme);

        jBtnAdd.setText("+");

        jBtnRemove.setText("-");

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTableLayout.createSequentialGroup()
                        .addComponent(jBtnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRemove))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTable);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnRemove;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTeme;
    // End of variables declaration//GEN-END:variables
    private PButtonsNew jPanelButtonsNew;

    @Override
    public void close() {
        dispose();
    }

    @Override
    public void setMessage(String signal) {
        JOptionPane.showMessageDialog(rootPane, signal);
    }

    public void initButtonsNew() {
        jPanelButtonsNew = new PButtonsNew();
        jPanelButtonsNew.setVisible(true);
        this.add(jPanelButtonsNew, BoxLayout.Y_AXIS);
    }

    @Override
    public JButton getSave() {
        return jPanelButtonsNew.getjBtnSave();
    }

    @Override
    public JButton getUpdate() {
        return jPanelButtonsNew.getjBtnUpdate();
    }

    @Override
    public JButton getEdit() {
        return jPanelButtonsNew.getJbtnEdit();
    }

    @Override
    public JButton getCancel() {
        return jPanelButtonsNew.getjBtnCancel();
    }

    public javax.swing.JTable getjTableTeme() {
        return jTableTeme;
    }

    public javax.swing.JButton getjBtnAdd() {
        return jBtnAdd;
    }

    public javax.swing.JButton getjBtnRemove() {
        return jBtnRemove;
    }


}
