/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.form;

import rs.ac.bg.fion.silab.gui.general.GeneralGUISearch;
import rs.ac.bg.fion.silab.gui.general.GeneralGUI;
import java.awt.BorderLayout;
import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author MARINA
 */
public class FTemaDiplomskogRadaSearch extends javax.swing.JDialog implements GeneralGUI, GeneralGUISearch {

    /**
     * Creates new form FTemaDiplomskogRada
     */
    public FTemaDiplomskogRadaSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorth = new javax.swing.JPanel();
        jPanelID = new javax.swing.JPanel();
        jCheckBoxAdvancedSearch = new javax.swing.JCheckBox();
        jCheckBoxBasicSearch = new javax.swing.JCheckBox();
        jTxtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBtnAddNew = new javax.swing.JButton();
        jBtnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTeme = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelNorth.setLayout(new javax.swing.BoxLayout(jPanelNorth, javax.swing.BoxLayout.Y_AXIS));

        jCheckBoxAdvancedSearch.setText("Advanced search");

        jCheckBoxBasicSearch.setText("Basic Search");

        jLabel1.setText("ID:");

        jBtnAddNew.setText("Add new ");

        jBtnRefresh.setText("Refesh");

        javax.swing.GroupLayout jPanelIDLayout = new javax.swing.GroupLayout(jPanelID);
        jPanelID.setLayout(jPanelIDLayout);
        jPanelIDLayout.setHorizontalGroup(
            jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelIDLayout.createSequentialGroup()
                        .addComponent(jBtnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jCheckBoxAdvancedSearch)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxBasicSearch))
                    .addGroup(jPanelIDLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtID)))
                .addContainerGap())
        );
        jPanelIDLayout.setVerticalGroup(
            jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxAdvancedSearch)
                        .addComponent(jCheckBoxBasicSearch))
                    .addComponent(jBtnAddNew)
                    .addComponent(jBtnRefresh))
                .addGap(19, 19, 19))
        );

        jPanelNorth.add(jPanelID);

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.PAGE_START);

        jTableTeme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTeme);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddNew;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JCheckBox jCheckBoxAdvancedSearch;
    private javax.swing.JCheckBox jCheckBoxBasicSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelID;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTeme;
    private javax.swing.JTextField jTxtID;
    // End of variables declaration//GEN-END:variables

    private PButtonsSearch jPanelButtonsSearch;
    private PTemaBasicSearch basicSearchPanel;
    private PTemaAdvancedSearch advancedSearchPanel;

    @Override
    public void close() {
        dispose();
    }

    @Override
    public void setMessage(String signal) {
        JOptionPane.showMessageDialog(rootPane, signal);
    }

    public void initButtonsSearch() {
        jPanelButtonsSearch = new PButtonsSearch();
        jPanelButtonsSearch.setVisible(true);
        this.add(jPanelButtonsSearch, BorderLayout.SOUTH);
    }

    public void initSearchPanel() {
        basicSearchPanel = new PTemaBasicSearch();
        basicSearchPanel.setVisible(true);
        this.add(basicSearchPanel, BoxLayout.Y_AXIS);
    }

    public javax.swing.JTable getjTableTeme() {
        return jTableTeme;
    }

    @Override
    public JButton getView() {
        return jPanelButtonsSearch.getjBtnView();
    }

    @Override
    public JButton getSelect() {
        return jPanelButtonsSearch.getjBtnSelect();
    }

    @Override
    public JCheckBox getBasicSearchCheckbox() {
        return jCheckBoxBasicSearch;
    }

    @Override
    public JCheckBox getAdvancedSearchCheckbox() {
        return jCheckBoxAdvancedSearch;
    }

    @Override
    public void addBasicSearchPanel() {

        jPanelNorth.add(basicSearchPanel, BoxLayout.Y_AXIS);
        basicSearchPanel.setVisible(true);
        resizeSearchPanel();

    }

    @Override
    public void addAdvancedSearchPanel() {
        jPanelNorth.add(advancedSearchPanel, BoxLayout.Y_AXIS);
        advancedSearchPanel.setVisible(true);
        resizeSearchPanel();
    }

    @Override
    public void removeBasicSearchPanel() {
        jPanelNorth.remove(basicSearchPanel);
        basicSearchPanel.setVisible(false);
        resizeSearchPanel();
    }

    @Override
    public void removeAdvancedSearchPanel() {
        advancedSearchPanel.setVisible(false);
        jPanelNorth.remove(advancedSearchPanel);
        resizeSearchPanel();
    }

    private void resizeSearchPanel() {

        int height = jPanelID.getPreferredSize().height;

        if (basicSearchPanel.isVisible()) {
            height += basicSearchPanel.getPreferredSize().height;
        }
        if (advancedSearchPanel.isVisible()) {
            height += advancedSearchPanel.getPreferredSize().height;
        }
        jPanelNorth.setPreferredSize(new Dimension(WIDTH, height));
        revalidate();
    }

    public javax.swing.JPanel getjPanelID() {
        return jPanelID;
    }

    public javax.swing.JTextField getjTxtID() {
        return jTxtID;
    }

    public PTemaBasicSearch getBasicSearchPanel() {
        return basicSearchPanel;
    }

    public void setBasicSearchPanel(PTemaBasicSearch basicSearchPanel) {
        this.basicSearchPanel = basicSearchPanel;
    }

    public PTemaAdvancedSearch getAdvancedSearchPanel() {
        return advancedSearchPanel;
    }

    public void setAdvancedSearchPanel(PTemaAdvancedSearch advancedSearchPanel) {
        this.advancedSearchPanel = advancedSearchPanel;
    }

    private void initPanels() {
        basicSearchPanel = new PTemaBasicSearch();
        advancedSearchPanel = new PTemaAdvancedSearch();
        basicSearchPanel.setVisible(false);
        advancedSearchPanel.setVisible(false);
    }

    public javax.swing.JButton getjBtnAddNew() {
        return jBtnAddNew;
    }

    public javax.swing.JButton getjBtnRefresh() {
        return jBtnRefresh;
    }
    
    
    
    
}
