/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.form;


import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author MARINA
 */
public class PStudentSearchAdvanced extends javax.swing.JPanel {

    /**
     * Creates new form PStudentSearchAdvanced
     */
    public PStudentSearchAdvanced() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupBudzet = new javax.swing.ButtonGroup();
        btnGroupPrviPutUpisao = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jTxtJMBG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonBudzetDa = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonBudzetNe = new javax.swing.JRadioButton();
        jRadioButtonBudzetSvi = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonPrviPutUpisaoDa = new javax.swing.JRadioButton();
        jRadioButtonPrviPutUpisaoNe = new javax.swing.JRadioButton();
        jRadioButtonPrviPutUpisaoSvi = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jBtnCheck = new javax.swing.JButton();
        jBtnUncheck = new javax.swing.JButton();

        jLabel2.setText("JMBG:");

        jLabel6.setText("Godina studija:");

        btnGroupBudzet.add(jRadioButtonBudzetDa);
        jRadioButtonBudzetDa.setText("Da");

        jLabel1.setText("Budzet:");

        btnGroupBudzet.add(jRadioButtonBudzetNe);
        jRadioButtonBudzetNe.setText("Ne");

        btnGroupBudzet.add(jRadioButtonBudzetSvi);
        jRadioButtonBudzetSvi.setSelected(true);
        jRadioButtonBudzetSvi.setText("Svi");

        jLabel3.setText("Prvi put upisao:");

        btnGroupPrviPutUpisao.add(jRadioButtonPrviPutUpisaoDa);
        jRadioButtonPrviPutUpisaoDa.setText("Da");

        btnGroupPrviPutUpisao.add(jRadioButtonPrviPutUpisaoNe);
        jRadioButtonPrviPutUpisaoNe.setText("Ne");

        btnGroupPrviPutUpisao.add(jRadioButtonPrviPutUpisaoSvi);
        jRadioButtonPrviPutUpisaoSvi.setSelected(true);
        jRadioButtonPrviPutUpisaoSvi.setText("Svi");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("1");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("2");

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("3");

        jCheckBox4.setSelected(true);
        jCheckBox4.setText("4");

        jBtnCheck.setText("Check all");
        jBtnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCheckActionPerformed(evt);
            }
        });

        jBtnUncheck.setText("Uncheck all");
        jBtnUncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUncheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtJMBG)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonBudzetDa)
                                    .addComponent(jRadioButtonPrviPutUpisaoDa))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonPrviPutUpisaoNe)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonPrviPutUpisaoSvi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonBudzetNe)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonBudzetSvi))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnUncheck)))
                        .addGap(0, 276, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox4)
                                .addComponent(jBtnCheck)
                                .addComponent(jBtnUncheck)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonBudzetDa)
                            .addComponent(jRadioButtonBudzetNe)
                            .addComponent(jRadioButtonBudzetSvi)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPrviPutUpisaoSvi)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButtonPrviPutUpisaoDa)
                    .addComponent(jRadioButtonPrviPutUpisaoNe))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCheckActionPerformed
        jCheckBox1.setSelected(true);
        jCheckBox2.setSelected(true);
        jCheckBox3.setSelected(true);
        jCheckBox4.setSelected(true);
    }//GEN-LAST:event_jBtnCheckActionPerformed

    private void jBtnUncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUncheckActionPerformed
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
    }//GEN-LAST:event_jBtnUncheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupBudzet;
    private javax.swing.ButtonGroup btnGroupPrviPutUpisao;
    private javax.swing.JButton jBtnCheck;
    private javax.swing.JButton jBtnUncheck;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButtonBudzetDa;
    private javax.swing.JRadioButton jRadioButtonBudzetNe;
    private javax.swing.JRadioButton jRadioButtonBudzetSvi;
    private javax.swing.JRadioButton jRadioButtonPrviPutUpisaoDa;
    private javax.swing.JRadioButton jRadioButtonPrviPutUpisaoNe;
    private javax.swing.JRadioButton jRadioButtonPrviPutUpisaoSvi;
    private javax.swing.JTextField jTxtJMBG;
    // End of variables declaration//GEN-END:variables

    

    public JTextField getjTxtJMBG() {
        return jTxtJMBG;
    }

    public javax.swing.JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    public javax.swing.JCheckBox getjCheckBox2() {
        return jCheckBox2;
    }

    public javax.swing.JCheckBox getjCheckBox3() {
        return jCheckBox3;
    }

    public javax.swing.JCheckBox getjCheckBox4() {
        return jCheckBox4;
    }
    
    public JCheckBox [] getCheckBoxesGodinaStudija(){
        return new JCheckBox[]{jCheckBox1,jCheckBox2,jCheckBox3,jCheckBox4};
    }

    public javax.swing.JRadioButton getjRadioButtonBudzetDa() {
        return jRadioButtonBudzetDa;
    }

    public javax.swing.JRadioButton getjRadioButtonBudzetNe() {
        return jRadioButtonBudzetNe;
    }

    public javax.swing.JRadioButton getjRadioButtonBudzetSvi() {
        return jRadioButtonBudzetSvi;
    }

    public javax.swing.JRadioButton getjRadioButtonPrviPutUpisaoDa() {
        return jRadioButtonPrviPutUpisaoDa;
    }

    public javax.swing.JRadioButton getjRadioButtonPrviPutUpisaoNe() {
        return jRadioButtonPrviPutUpisaoNe;
    }

    public javax.swing.JRadioButton getjRadioButtonPrviPutUpisaoSvi() {
        return jRadioButtonPrviPutUpisaoSvi;
    }

    public JRadioButton getSelectedBudzet() {
        if(jRadioButtonBudzetDa.isSelected()) return jRadioButtonBudzetDa;
        if(jRadioButtonBudzetNe.isSelected()) return jRadioButtonBudzetNe;
        return jRadioButtonBudzetSvi;
    }

    public JRadioButton getPrviPutUpisao(){
        if(jRadioButtonPrviPutUpisaoDa.isSelected())return jRadioButtonPrviPutUpisaoDa;
        if(jRadioButtonPrviPutUpisaoNe.isSelected())return jRadioButtonPrviPutUpisaoNe;
        return jRadioButtonPrviPutUpisaoSvi;
    }
    
    
}
